services:
  app:
    container_name: trade-matrix-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # web endpoint
      - "5006:5005" # debug port
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tmatrix
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret

  db:
    container_name: tmatrix-db
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tmatrix
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
      - ./utils/mysql/schema/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql
      - ./utils/mysql/data/01_address.sql:/docker-entrypoint-initdb.d/01_address.sql
      - ./utils/mysql/data/02_user.sql:/docker-entrypoint-initdb.d/02_user.sql
      - ./utils/mysql/data/03_user-address.sql:/docker-entrypoint-initdb.d/03_user-address.sql
      - ./utils/mysql/data/04_user-role.sql:/docker-entrypoint-initdb.d/04_user-role.sql
      - ./utils/mysql/data/05_account.sql:/docker-entrypoint-initdb.d/05_account.sql
      - ./utils/mysql/data/06_currency.sql:/docker-entrypoint-initdb.d/06_currency.sql
      - ./utils/mysql/data/07_currency_exchange_rate.sql:/docker-entrypoint-initdb.d/07_currency_exchange_rate.sql
      - ./utils/mysql/data/08_wallet.sql:/docker-entrypoint-initdb.d/08_wallet.sql
      - ./utils/mysql/data/09_market.sql:/docker-entrypoint-initdb.d/09_market.sql
      - ./utils/mysql/data/10_product.sql:/docker-entrypoint-initdb.d/10_product.sql
      - ./utils/mysql/data/11_market_product.sql:/docker-entrypoint-initdb.d/11_market_product.sql
      - ./utils/mysql/data/12_product_price_history.sql:/docker-entrypoint-initdb.d/12_product_price_history.sql
      - ./utils/mysql/data/13_portfolio.sql:/docker-entrypoint-initdb.d/13_portfolio.sql
      - ./utils/mysql/data/14_position.sql:/docker-entrypoint-initdb.d/14_position.sql
      - ./utils/mysql/data/15_order.sql:/docker-entrypoint-initdb.d/15_order.sql
      - ./utils/mysql/data/16_transaction.sql:/docker-entrypoint-initdb.d/16_transaction.sql

volumes:
  db-data:
