spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    # syntax compatibility with mysql
    url: jdbc:hsqldb:mem:tmatrix;sql.syntax_mys=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # apply new changes to entities


      # run mysql container
      # docker run --name mprocs -e MYSQL_ROOT_PASSWORD=12345 -p 3306:3306 -v /Users/rafa95/Dev/volumes/mproc-swift:/var/lib/mysql -d mysql
