spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    # mysql docker container address
    url: jdbc:mysql://db:3306/tmatrix
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # From hikari docs: "A value less than zero will bypass any initial connection attempt,
      # and the pool will start immediately while trying to obtain connections in the background.
      # Consequently, later efforts to obtain a connection may fail. https://github.com/brettwooldridge/HikariCP#infrequently-used"
      # Used for docker-compose setups
      # On start of both containers: The app will keep trying to acquire a connection in the background without exiting.
      initialization-fail-timeout: -1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    org.springframework: DEBUG

#R8HWBA167JXNVQDP
